sudo: required
language: scala
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.coursier

script:
  - curl -L -o ~/bin/mill "https://dl.bintray.com/guilgaly/generic/0.2.0-16-cb327e/mill" && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - git clean -xdf
  - mill __.reformat
  - git diff-index --quiet HEAD
  - mill _.test
