version: 2.1

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch-node
    working_directory: /tmp/itunes-dap-sync
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb

jobs:
  build:
    executor: openjdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-coursier-{{ checksum "dependencies.sc" }}
            - v1-coursier-
      - run: ./.circleci/build.sh
      - save_cache:
          key: v1-coursier-{{ checksum "dependencies.sc" }}
          paths:
            - ~/.cache/coursier

workflows:
  version: 2
  build:
    jobs:
      - build:
          name: "Build"
